### ISSUE TITLE
protoc

### ISSUE THREAD

**Issue by unicomp21** [PragmaTwice/protopuf#36]
can we enable discussions on this repo?

how do I generate a .proto file from protopuf?  or vice versa?  suggestions?

**Comment by PragmaTwice** [comment]
> can we enable discussions on this repo?

Sure! It is enabled now.

> how do I generate a .proto file from protopuf? or vice versa? suggestions?

It may be complicated to translate c++ type definitions of protopuf messages to `.proto` message definitions,
since c++ type system is complex and you may need libClang to parsing and analyzing semantics of C++ code.

But translating `.proto` message definitions to protopuf c++ types is more easy,
since the proto language is descriptive and simple,  and you can write a protoc plug-in or use some parser generaters to parse `.proto` and then generate some corresponding c++ code.

I actually planned to write a translator to convert from `.proto` to protopuf c++ type definitions, but I don't have time to move forward with this work at the moment.

Ideas and suggestions are always welcome!

**Comment by unicomp21** [comment]
Makes sense, thanks @PragmaTwice !

This is a beautiful header lib, wish protobuf had been implemented this way in the first place, lol.

Thanks!
