### ISSUE TITLE
Out of bounds write/read in encode/decode functions

### ISSUE THREAD

**Issue by pet74alex** [PragmaTwice/protopuf#41]
`encode` familу of functions doesn't not perform span size check, so it can cause out of bounds write when the buffer size is not enough for serialization of the message.

`decode` family of functions also can read out of span bounds when the encoded message unexpectedly ended in the middle of some value being deserialized. 

Both mentioned function families need to be fixed.

**Comment by PragmaTwice** [comment]
Yeah the current implementation didn't introduce a good error handling architecture.

We can refactor the interface first to something like `decode(..) -> Result<.., Error>` (since I'm not a fan of exceptions), and then we can add many error checks here.

However I'm sorry that I don't have enough time currently for this project. Feel free to do that if you want.

**Comment by dngrudin** [comment]
Created a PR #42  with the implementation of checking for out-of-bounds. @PragmaTwice Please check.

**Comment by PragmaTwice** [comment]
Thank you. Closed due to merged.
